### ISSUE TITLE
PowerPoint compatibility of this tweaks ?

### ISSUE THREAD

**Issue by GlitchedCod** [matafokka/ExcelDarkThemeFix#5] opened 2021-05-20 13:10 UTC
Hi !

A very huge thanks for this fix for Excel but I'm asking myself if this is possible to port this to PowerPont too since i use it a lot more than Excel ? Shapes with a color will be black instead of blue and even if you choose white and this even happen in slideshow mode and in .MP4 convert. They are files for PowerPoint plugin with .plam instead of .xlam, I have tried it out in PowerPoint, but it didn't have any effects (just an error saying that he can't read the plugin). This is the only things that force me to use the default Windows theme and I'll be very happy to use my softwares as usual with a more simple theme than the Windows one. Sorry for mispelling i'm French so this is hard for me to write this !

Well thanks to have read my request, finger crossed ! Amazing job still.

**Comment by matafokka** [comment] 2021-05-20 14:51
Bonjour! Thank you for your request and such kind words, I appreciate it!

Which version of MS Office are you using? I haven't encountered such a problem with MS Office 2019 and, I think, 2016 has been working fine too.

Your issue also might have happened because you're working with files created by old PowerPoint versions or LibreOffice. Can you send some of the files that you have a problem with?

Anyway, I believe, it is possible to port this Add-In to PowerPoint and, if we're lucky, to do it by just copying the code from Excel to PowerPoint *(not by renaming file though, VBA is a compiled language)*.

Unfortunately, I'm currently busy with the uni but I'll try my best when I'll have a spare time *(though, it won't happen any time soon, so there will be no ETA)*.

I'll close this issue for now but I promise to write back here when I'll try to port the code.

P.S. Your English is very good, don't be shy about it ;)

**Closed as completed by matafokka** 2021-05-20 14:51 UTC

**Comment by GlitchedCod** [comment] 2021-05-28 19:25
I was having this bug with Office 2016 and now since i have updated Office 2021 Preview. Files was only made from Office_because LibreOffice s*ck and i don't have it_, the latest file made and one week before my request.
When I made a shape the blue color inside work by default but then if you try using white or black it will change to the one that your theme has decided. This happend in Word too with text I think (not sure about that) and of course shapes.
Thank you for your time to see if my problem can be solved !

**Comment by matafokka** [comment] 2021-05-28 19:36
Gosh, it sucks if MS is back at using system colors everywhere again. If this issue will be present in the final release, I'll try my best to fix both Word and PowerPoint.

For now, I highly suggest to use 2019 version since it shouldn't have said issues.

Thanks for the report, I'll update my office as soon as the release will be ready and see how it goes.

**Comment by matafokka** [comment] 2021-06-07 19:48
Hey, a quick update on your issue.

Looks like PowerPoint doesn't even have automatic color, and all default themes and color schemes (except Savon which hardly anyone uses) works just fine. So I can't reproduce your issue.

However, there is a problem with Word. Auto text color in shapes is indeed wrong. There also was a bug (all text had wrong color) with files created in older Word version or LibreOffice, can't remember which one. But, I think, such a minor issue isn't worth fixing since everyone just changes colors later. If you're using custom styles, just change text color in them.

I've tested on Windows 7 x64, Office 2016 Build 12026.20320. I'll try Windows 10 a bit later but I doubt that anything will change.

Can you share some of your files both for PowerPoint and Word, so I can see if problem is related to it? Just drop them in the comment here.

**Comment by GlitchedCod** [comment] 2021-06-08 18:03
The video of me creating a new file with Office 2021 Windows 10 latest release and a shape with "black" color on it : [The video](https://www.screenpresso.com/=LqPpe)
I use the theme Arc-darker of [this Deviantart](https://www.deviantart.com/niivu/art/ARC-X-Windows-10-Theme-772549960)
The file itself (saved right after the video) : [TEST color bug presentation.pptx](https://github.com/matafokka/ExcelDarkThemeFix/files/6618652/TEST.color.bug.presentation.pptx)
A Word document even if I don't really use them : [TEST 2.docx](https://github.com/matafokka/ExcelDarkThemeFix/files/6618705/TEST.2.docx)
In fact I have just tested right now and if I manually choose exactly black it is black but if I choose the button where is the black by defaults it isn't black, that's what I want to have fixed.
Thank you for your time !

**Comment by matafokka** [comment] 2021-06-08 18:25
Thank you, now I can confirm your issue, problem indeed exists and can be reproduced. It surely can be fixed but it'll most likely require a user to click a button, just like in ExcelDarkThemeFix. To our misfortune, it can't be automated because shapes doesn't have any events and VBA doesn't provide mechanisms to change default color pallet.

So what do you think, will new Add-In be useful?

**Comment by GlitchedCod** [comment] 2021-06-08 18:31
If we can add a menu that looks like the color palette and with the ribbon just drop it as is, yes this can help me a lot !

**Comment by matafokka** [comment] 2021-06-08 18:42
Good idea, looks like it's possible _(sorry, not a big VBA expert, had to look it up :p)_, so I'll start working on it ASAP. Still no ETA though, sorry.

**Comment by GlitchedCod** [comment] 2021-06-08 18:43
ETA ?

**Comment by matafokka** [comment] 2021-06-08 18:45
Estimated time of arrival, means when something will be ready

**Comment by GlitchedCod** [comment] 2021-06-08 18:49
Well it's still better than nothing and as this has been  1 year without using theme because of this issue well you can take one or two years to do that 😆

**Comment by matafokka** [comment] 2021-06-08 18:53
Well, you still can use light themes, they shouldn't affect colors that much. New Add-In will take around a month (a year is too much for that :D), depends on when I'll be done with my uni.

**Comment by matafokka** [comment] 2021-07-30 21:46
Hey there! Sorry for the delay, my uni projects are taking lotta time.

Finally got my hands on your issue, [check new Add-In out](https://github.com/matafokka/PowerPointDarkThemeFix)!

**Comment by GlitchedCod** [comment] 2021-08-02 21:08
> Hey there! Sorry for the delay, my uni projects are taking lotta time.
> 
> Finally got my hands on your issue, [check new Add-In out](https://github.com/matafokka/PowerPointDarkThemeFix)!

Well thank you a lot ! Since I'm in vacation and that I've had disabled themes on my PC for this problem (and some anothers) it will take a moment before I would be actually able to play with it and FINALLY have a REAL Windows interface ! I am very greatful of your work on this and I really want to test that out ! Thanks for your time on this tweak, good day to you !

**Comment by matafokka** [comment] 2021-08-02 21:13
Thank you for your kind words! Can't wait for your feedback, hope it'll work fine :)

Have a good time on your vacation!
